import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { loadAdminCampaigns, loadCampaignFormOptions, createAdminHomepageCampaign, updateAdminHomepageCampaign, setAdminHomepageCampaignStatus, type AdminCampaignRow } from "@/lib/admin/campaign.functions";
import { getAdminAccessState } from "./access.functions";

type CampaignProduct = { id:string; merchant_id:string; name:string; category:string; listing_type:string; stock:number };
type CampaignMerchant = { id:string; name:string; city:string|null };
type CampaignPageData = {
  access: Awaited<ReturnType<typeof getAdminAccessState>>;
  campaigns: AdminCampaignRow[];
  options: { merchants: CampaignMerchant[]; products: CampaignProduct[] };
};

export const Route=createFileRoute("/admin/campaigns")({
  loader: async(): Promise<CampaignPageData>=>{const [access,campaigns,options]=await Promise.all([getAdminAccessState(),loadAdminCampaigns(),loadCampaignFormOptions()]);return {access,campaigns,options};},
  head:()=>({meta:[{name:"robots",content:"noindex,nofollow,noarchive"}]}),
  component: AdminCampaigns,
});

type FormState={merchantId:string;productId:string;name:string;title:string;subtitle:string;imagePath:string;ctaLabel:string;placement:"sponsored_ads"|"food_spotlight";startsAt:string;endsAt:string;targetCity:string;targetCategory:string;priority:string;maxImpressions:string;mobileVisible:boolean;desktopVisible:boolean;adminNotes:string};
const empty:FormState={merchantId:"",productId:"",name:"",title:"",subtitle:"",imagePath:"",ctaLabel:"Shop now",placement:"sponsored_ads",startsAt:"",endsAt:"",targetCity:"",targetCategory:"",priority:"100",maxImpressions:"",mobileVisible:true,desktopVisible:true,adminNotes:""};
function AdminCampaigns(){
 const {access,campaigns,options}: CampaignPageData=Route.useLoaderData(); const [form,setForm]=useState<FormState>(empty); const [editing,setEditing]=useState<AdminCampaignRow|null>(null); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [filter,setFilter]=useState("all");
 const products=useMemo(()=>options.products.filter((p:CampaignProduct)=>!form.merchantId||p.merchant_id===form.merchantId),[options.products,form.merchantId]);
 const filtered=campaigns.filter((c:AdminCampaignRow)=>filter==="all"||c.status===filter);
 if(!access.authenticated||!access.isAdmin)return <main className="grid min-h-screen place-items-center"><p>Administrator access required.</p></main>;
 function reset(){setEditing(null);setForm(empty);setMessage("");}
 function edit(c:AdminCampaignRow){setEditing(c);setForm({merchantId:c.merchantId,productId:c.productId??"",name:c.name,title:c.title,subtitle:c.subtitle??"",imagePath:c.imagePath??"",ctaLabel:c.ctaLabel??"Shop now",placement:c.placement as FormState["placement"],startsAt:c.startsAt.slice(0,16),endsAt:c.endsAt.slice(0,16),targetCity:c.targetCity??"",targetCategory:c.targetCategory??"",priority:String(c.priority),maxImpressions:c.maxImpressions==null?"":String(c.maxImpressions),mobileVisible:c.mobileVisible,desktopVisible:c.desktopVisible,adminNotes:c.adminNotes??""});window.scrollTo({top:0,behavior:"smooth"});}
 async function save(){setBusy(true);setMessage("");try{if(form.placement==="food_spotlight"&&!form.productId)throw new Error("Food Spotlight requires a product.");const data={merchantId:form.merchantId,productId:form.productId||undefined,name:form.name,title:form.title,subtitle:form.subtitle||undefined,imagePath:form.imagePath||undefined,ctaLabel:form.ctaLabel||undefined,destination:{type:"product" as const,id:form.productId},placement:form.placement,startsAt:new Date(form.startsAt).toISOString(),endsAt:new Date(form.endsAt).toISOString(),targetCity:form.targetCity||undefined,targetCategory:form.targetCategory||undefined,priority:Number(form.priority),maxImpressions:form.maxImpressions?Number(form.maxImpressions):null,mobileVisible:form.mobileVisible,desktopVisible:form.desktopVisible,adminNotes:form.adminNotes||undefined};if(editing)await updateAdminHomepageCampaign({data:{...data,campaignId:editing.id,expectedVersion:editing.version}});else await createAdminHomepageCampaign({data});window.location.reload();}catch(e){setMessage(e instanceof Error?e.message:"Campaign save failed");}finally{setBusy(false);}}
 async function act(c:AdminCampaignRow,action:"approve"|"pause"|"resume"|"reject"|"archive"|"end"){setBusy(true);setMessage("");try{const reason=action==="reject"?prompt("Rejection reason")??"":undefined;await setAdminHomepageCampaignStatus({data:{campaignId:c.id,action,reason,expectedVersion:c.version}});window.location.reload();}catch(e){setMessage(e instanceof Error?e.message:"Campaign action failed");}finally{setBusy(false);}}
 return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.16em] text-market-muted">Admin merchandising</p><h1 className="mt-2 text-3xl font-black">Campaign Manager</h1><p className="mt-2 max-w-3xl text-sm text-market-muted">Create controlled homepage campaigns for Sponsored placements and Food Spotlight. Campaigns start as drafts and cannot appear publicly until approved.</p></div><a href="/admin/dashboard" className="rounded-xl border border-market-line px-4 py-2 text-sm font-bold">Back to dashboard</a></div>
 {message?<p className="mt-5 rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700">{message}</p>:null}
 <section className="mt-8 rounded-2xl border border-market-line bg-white p-6 shadow-market"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">{editing?"Edit campaign":"Create campaign"}</h2><p className="mt-1 text-sm text-market-muted">Server validation enforces merchant, product, Food category and scheduling rules.</p></div>{editing?<button onClick={reset} className="rounded-xl border px-3 py-2 text-xs font-bold">Cancel edit</button>:null}</div>
 <div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">
  <label className="text-sm font-bold">Merchant<select value={form.merchantId} onChange={e=>setForm(v=>({...v,merchantId:e.target.value,productId:""}))} className="mt-2 h-11 w-full rounded-xl border border-market-line px-3 font-normal"><option value="">Select verified merchant</option>{options.merchants.map((m:any)=><option key={m.id} value={m.id}>{m.name}{m.city?` · ${m.city}`:""}</option>)}</select></label>
  <label className="text-sm font-bold">Placement<select value={form.placement} onChange={e=>setForm(v=>({...v,placement:e.target.value as FormState["placement"]}))} className="mt-2 h-11 w-full rounded-xl border border-market-line px-3 font-normal"><option value="sponsored_ads">Sponsored Ads</option><option value="food_spotlight">Food Spotlight</option></select></label>
  <label className="text-sm font-bold">Product / destination<select value={form.productId} onChange={e=>setForm(v=>({...v,productId:e.target.value}))} className="mt-2 h-11 w-full rounded-xl border border-market-line px-3 font-normal"><option value="">Select product</option>{products.map((p:any)=><option key={p.id} value={p.id}>{p.name} · {p.category}{p.listing_type==="food"?" · Food":""}</option>)}</select></label>
  <label className="text-sm font-bold">Internal campaign name<input value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))} maxLength={120} className="mt-2 h-11 w-full rounded-xl border px-3 font-normal" placeholder="Weekend Food Spotlight"/></label>
  <label className="text-sm font-bold">Public title<input value={form.title} onChange={e=>setForm(v=>({...v,title:e.target.value}))} maxLength={120} className="mt-2 h-11 w-full rounded-xl border px-3 font-normal" placeholder="Fresh meals near you"/></label>
  <label className="text-sm font-bold">Subtitle<input value={form.subtitle} onChange={e=>setForm(v=>({...v,subtitle:e.target.value}))} maxLength={180} className="mt-2 h-11 w-full rounded-xl border px-3 font-normal"/></label>
  <label className="text-sm font-bold">CTA<input value={form.ctaLabel} onChange={e=>setForm(v=>({...v,ctaLabel:e.target.value}))} maxLength={40} className="mt-2 h-11 w-full rounded-xl border px-3 font-normal"/></label>
  <label className="text-sm font-bold">Image path<input value={form.imagePath} onChange={e=>setForm(v=>({...v,imagePath:e.target.value}))} maxLength={500} className="mt-2 h-11 w-full rounded-xl border px-3 font-normal" placeholder="/uploads/campaigns/hero.webp"/></label>
  <label className="text-sm font-bold">Target city<input value={form.targetCity} onChange={e=>setForm(v=>({...v,targetCity:e.target.value}))} maxLength={80} className="mt-2 h-11 w-full rounded-xl border px-3 font-normal" placeholder="Accra"/></label>
  <label className="text-sm font-bold">Target category<input value={form.targetCategory} onChange={e=>setForm(v=>({...v,targetCategory:e.target.value}))} maxLength={80} className="mt-2 h-11 w-full rounded-xl border px-3 font-normal" placeholder="Food"/></label>
  <label className="text-sm font-bold">Priority<input type="number" min="0" max="10000" value={form.priority} onChange={e=>setForm(v=>({...v,priority:e.target.value}))} className="mt-2 h-11 w-full rounded-xl border px-3 font-normal"/></label>
  <label className="text-sm font-bold">Impression cap<input type="number" min="1" max="1000000000" value={form.maxImpressions} onChange={e=>setForm(v=>({...v,maxImpressions:e.target.value}))} className="mt-2 h-11 w-full rounded-xl border px-3 font-normal" placeholder="Optional"/></label>
  <label className="text-sm font-bold">Starts<input type="datetime-local" value={form.startsAt} onChange={e=>setForm(v=>({...v,startsAt:e.target.value}))} className="mt-2 h-11 w-full rounded-xl border px-3 font-normal"/></label>
  <label className="text-sm font-bold">Ends<input type="datetime-local" value={form.endsAt} onChange={e=>setForm(v=>({...v,endsAt:e.target.value}))} className="mt-2 h-11 w-full rounded-xl border px-3 font-normal"/></label>
 </div>
 <div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-sm font-bold">Admin notes<textarea value={form.adminNotes} onChange={e=>setForm(v=>({...v,adminNotes:e.target.value}))} maxLength={2000} className="mt-2 min-h-24 w-full rounded-xl border px-3 py-2 font-normal"/></label><div className="rounded-xl bg-market-soft p-4 text-sm"><p className="font-black">Safety rules</p><ul className="mt-2 list-disc space-y-1 pl-5 text-market-muted"><li>No arbitrary HTML, scripts or external media.</li><li>Food Spotlight accepts only active food products.</li><li>Only active verified merchants can be promoted.</li><li>Campaigns are drafts until explicitly approved.</li></ul></div></div>
 <div className="mt-4 flex flex-wrap gap-4 text-sm font-semibold"><label><input type="checkbox" checked={form.mobileVisible} onChange={e=>setForm(v=>({...v,mobileVisible:e.target.checked}))}/> Mobile</label><label><input type="checkbox" checked={form.desktopVisible} onChange={e=>setForm(v=>({...v,desktopVisible:e.target.checked}))}/> Desktop</label></div>
 <button disabled={busy} onClick={()=>void save()} className="mt-6 rounded-xl bg-market-green px-5 py-3 text-sm font-black text-white disabled:opacity-50">{busy?"Saving…":editing?"Save campaign":"Create draft"}</button>
 </section>
 <section className="mt-8 rounded-2xl border border-market-line bg-white p-6 shadow-market"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">Campaigns</h2><p className="mt-1 text-sm text-market-muted">Review status, schedule, performance and lifecycle controls.</p></div><select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-xl border px-3 py-2 text-sm"><option value="all">All</option>{["draft","pending_review","scheduled","active","paused","rejected","ended","archived"].map(s=><option key={s} value={s}>{s}</option>)}</select></div>
 <div className="mt-6 space-y-4">{filtered.length===0?<p className="rounded-xl border p-5 text-sm text-market-muted">No campaigns in this view.</p>:filtered.map((c:any)=><article key={c.id} className="rounded-2xl border border-market-line p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-black">{c.title}</h3><span className="rounded-full border px-2 py-1 text-[11px] font-bold">{c.status}</span><span className="rounded-full bg-market-soft px-2 py-1 text-[11px] font-bold">{c.placement}</span></div><p className="mt-1 text-xs text-market-muted">{c.merchantName} · {c.productName??c.destinationId}</p><p className="mt-1 text-xs text-market-muted">{new Date(c.startsAt).toLocaleString()} → {new Date(c.endsAt).toLocaleString()} · priority {c.priority}</p></div><div className="text-right text-xs"><p><b>{c.impressionCount}</b> impressions</p><p><b>{c.clickCount}</b> clicks · CTR {c.impressionCount?((c.clickCount/c.impressionCount)*100).toFixed(2):"0.00"}%</p></div></div><div className="mt-4 flex flex-wrap gap-2">{["draft","pending_review","scheduled","paused","rejected"].includes(c.status)?<button disabled={busy} onClick={()=>edit(c)} className="rounded-lg border px-3 py-2 text-xs font-bold">Edit</button>:null}{c.status==="draft"||c.status==="pending_review"||c.status==="rejected"?<button disabled={busy} onClick={()=>void act(c,"approve")} className="rounded-lg bg-market-green px-3 py-2 text-xs font-bold text-white">Approve</button>:null}{c.status==="active"?<button disabled={busy} onClick={()=>void act(c,"pause")} className="rounded-lg bg-amber-500 px-3 py-2 text-xs font-bold text-white">Pause</button>:null}{c.status==="paused"?<button disabled={busy} onClick={()=>void act(c,"resume")} className="rounded-lg bg-market-green px-3 py-2 text-xs font-bold text-white">Resume</button>:null}{["draft","pending_review","scheduled","paused"].includes(c.status)?<button disabled={busy} onClick={()=>void act(c,"reject")} className="rounded-lg border border-red-200 px-3 py-2 text-xs font-bold text-red-700">Reject</button>:null}{["draft","scheduled","paused","rejected"].includes(c.status)?<button disabled={busy} onClick={()=>void act(c,"archive")} className="rounded-lg border px-3 py-2 text-xs font-bold">Archive</button>:null}{c.status==="active"?<button disabled={busy} onClick={()=>void act(c,"end")} className="rounded-lg border border-red-200 px-3 py-2 text-xs font-bold text-red-700">End now</button>:null}</div></article>)}</div></section>
 </main>;
}
