import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const root=new URL('../',import.meta.url).pathname;
const read=(p)=>fs.readFileSync(root+p,'utf8');
test('enterprise sync uses replay-resistant HMAC authentication',()=>{const s=read('src/routes/api.enterprise.catalog.sync.ts'); assert.match(s,/authorizeInternalHmacRequest/); assert.doesNotMatch(s,/x-elemarket-sync-secret/);});
test('webhook binds by payment attempt reference',()=>{const s=read('migrations/0067_real_break_test_fixes.sql'); assert.match(s,/from payment_attempts pa join payments p/); assert.match(s,/pa\.provider_reference=p_provider_reference/);});
test('one open payment attempt is database unique',()=>{const s=read('migrations/0067_real_break_test_fixes.sql'); assert.match(s,/payment_attempts_one_open_per_payment_uq/);});
test('checkout product status is enforced at DB boundary',()=>{const s=read('migrations/0068_checkout_status_and_auth_hardening.sql'); assert.match(s,/products p where p\.id=new\.product_id and p\.status='active'/);});
test('delivery ignores client coordinates',()=>{const s=read('src/lib/market/adapters/delivery.server.ts'); assert.doesNotMatch(s,/if \(input\.lat !== undefined && input\.lon !== undefined\) return input/);});
test('OTP cannot verify an arbitrary existing email row',()=>{const s=read('src/lib/auth/email/email-otp.server.ts'); assert.match(s,/where "id" = \$1 and lower\("email"\) = \$2/); assert.doesNotMatch(s,/coalesce\(\$1, \(select "id" from "user"/);});
test('SSRF accepts hostnames only for DNS validation, not as private IPs',()=>{const s=read('src/lib/security/ssrf.server.ts'); assert.match(s,/kind === 4 \? privateIpv4\(ip\) : kind === 6 \? privateIpv6\(ip\) : false/);});
test('SSRF endpoint validation is awaited on persistence path',()=>{const s=read('src/lib/market/enterprise-catalog.server.ts'); assert.match(s,/await validateEndpoint\(input\.endpointUrl\)/);});
test('cancellation blocks orders already handed to provider',()=>{const s=read('migrations/0068_checkout_status_and_auth_hardening.sql'); assert.match(s,/v_payment\.status<>'initiated' or v_payment\.provider_reference is not null/);});
test('payment expiry scheduler endpoint exists',()=>{assert.ok(fs.existsSync(root+'src/routes/api.internal.expire-payment-orders.ts'));});
test('signup OTP cannot bind to an existing account',()=>{const s=read('src/lib/auth/email/email-otp.server.ts'); assert.match(s,/input\.purpose === "signup"/); assert.match(s,/An account already exists/);});
test('OTP pumping is materially rate limited',()=>{const s=read('src/lib/auth/otp/otp.server.ts'); assert.match(s,/otp-request.*windowSeconds: 60, maxRequests: 5/); assert.match(s,/otp-request-destination.*windowSeconds: 600, maxRequests: 3/);});
test('preview settlement requires explicit development flag',()=>{const s=read('src/lib/market/payment.server.ts'); assert.match(s,/ELEMARKET_ENABLE_PREVIEW_SETTLEMENT/); assert.match(s,/getElemarketEnvironment\(\) !== "development"/);});
test('push notification navigation cannot leave origin',()=>{const s=read('public/firebase-messaging-sw.js'); assert.match(s,/parsed\.origin === self\.location\.origin/);});
test('enterprise fetch pins a validated public DNS address',()=>{const s=read('src/lib/market/enterprise-catalog.server.ts'); assert.match(s,/publicHttpsFetch/); const transport=read("src/lib/security/ssrf.server.ts"); assert.match(transport,/lookup:/); assert.match(transport,/rejectUnauthorized: true/);});
test('completed generic HTTP payments require provider verification',()=>{const s=read('src/lib/market/payment.server.ts'); assert.match(s,/Provider transaction verification is required/);});
test('generic HTTP payment adapter has transaction verification',()=>{const s=read('src/lib/market/adapters/payment.ts'); assert.match(s,/verifyTransaction/);});
test('Paystack event ids distinguish event type from transaction id',()=>{const s=read('src/lib/market/adapters/providers/paystack.ts'); assert.match(s,/eventId = providerEventId/);});
test('variant price history trigger reads currency from the parent product',()=>{const s=read('migrations/0069_variant_price_history_fix.sql'); assert.doesNotMatch(s,/new\.currency/); assert.match(s,/select new\.id,new\.product_id,new\.price,p\.currency,now\(\)/); assert.match(s,/from products p/); assert.match(s,/where p\.id=new\.product_id/);});
test('final variant price history repair recreates the trigger',()=>{const s=read('migrations/0079_variant_price_history_trigger_final_repair.sql'); assert.doesNotMatch(s,/new\.currency/); assert.match(s,/p\.currency/); assert.match(s,/drop trigger if exists variant_price_history_capture on product_variants/); assert.match(s,/create trigger variant_price_history_capture/);});
test('legacy direct storage URL helper cannot bypass upload intents',()=>{const s=read('src/lib/storage/storage.server.ts'); assert.match(s,/Direct storage upload URLs are disabled/);});
test('cleanup scheduler removes stale upload intents',()=>{const s=read('src/routes/api.internal.expire-payment-orders.ts'); assert.match(s,/storage_upload_intents/); assert.match(s,/deleteObject/);});
