/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCampaignsRouteImport } from './routes/admin/campaigns'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminSecurityRouteImport } from './routes/admin/security'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiSearchRouteImport } from './routes/api.search'
import { Route as MerchantDashboardRouteImport } from './routes/merchant/dashboard'
import { Route as MerchantLoginRouteImport } from './routes/merchant/login'
import { Route as MerchantRegisterRouteImport } from './routes/merchant/register'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as PaymentPreviewRouteImport } from './routes/payment.preview'
import { Route as PaymentReturnRouteImport } from './routes/payment.return'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders.index'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin/orders.$orderId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDeliveryQuoteRouteImport } from './routes/api.delivery.quote'
import { Route as ApiEmailWebhookRouteImport } from './routes/api.email.webhook'
import { Route as ApiInternalBrandIntegrationWorkerRouteImport } from './routes/api.internal.brand-integration-worker'
import { Route as ApiInternalEnterpriseOrderOutboxRouteImport } from './routes/api.internal.enterprise-order-outbox'
import { Route as ApiInternalEnterpriseWebhookWorkerRouteImport } from './routes/api.internal.enterprise-webhook-worker'
import { Route as ApiInternalExpirePaymentOrdersRouteImport } from './routes/api.internal.expire-payment-orders'
import { Route as ApiInternalSyncEnterpriseCatalogsRouteImport } from './routes/api.internal.sync-enterprise-catalogs'
import { Route as ApiMobileCatalogRouteImport } from './routes/api.mobile.catalog'
import { Route as ApiMobileCheckoutRouteImport } from './routes/api.mobile.checkout'
import { Route as ApiMobileDeliveryQuoteRouteImport } from './routes/api.mobile.delivery-quote'
import { Route as ApiMobileMeRouteImport } from './routes/api.mobile.me'
import { Route as ApiMobilePaymentIntentRouteImport } from './routes/api.mobile.payment-intent'
import { Route as ApiMobilePaymentStatusRouteImport } from './routes/api.mobile.payment-status'
import { Route as ApiMobileProfileRouteImport } from './routes/api.mobile.profile'
import { Route as ApiPaymentsWebhookRouteImport } from './routes/api.payments.webhook'
import { Route as ApiBrandIntegrationWebhookRouteImport } from './routes/api.brand.integration.webhook'
import { Route as ApiEnterpriseCatalogSyncRouteImport } from './routes/api.enterprise.catalog.sync'
import { Route as ApiEnterpriseCatalogWebhookRouteImport } from './routes/api.enterprise.catalog.webhook'
import { Route as ApiFinancingMerchantsMerchantIdHealthRouteImport } from './routes/api/financing/merchants/$merchantId.health'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/admin/campaigns',
  path: '/admin/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/admin/security',
  path: '/admin/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantDashboardRoute = MerchantDashboardRouteImport.update({
  id: '/merchant/dashboard',
  path: '/merchant/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantLoginRoute = MerchantLoginRouteImport.update({
  id: '/merchant/login',
  path: '/merchant/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRegisterRoute = MerchantRegisterRouteImport.update({
  id: '/merchant/register',
  path: '/merchant/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRoute,
} as any)
const PaymentPreviewRoute = PaymentPreviewRouteImport.update({
  id: '/payment/preview',
  path: '/payment/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentReturnRoute = PaymentReturnRouteImport.update({
  id: '/payment/return',
  path: '/payment/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/admin/orders/',
  path: '/admin/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/admin/orders/$orderId',
  path: '/admin/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeliveryQuoteRoute = ApiDeliveryQuoteRouteImport.update({
  id: '/api/delivery/quote',
  path: '/api/delivery/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailWebhookRoute = ApiEmailWebhookRouteImport.update({
  id: '/api/email/webhook',
  path: '/api/email/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalBrandIntegrationWorkerRoute =
  ApiInternalBrandIntegrationWorkerRouteImport.update({
    id: '/api/internal/brand-integration-worker',
    path: '/api/internal/brand-integration-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalEnterpriseOrderOutboxRoute =
  ApiInternalEnterpriseOrderOutboxRouteImport.update({
    id: '/api/internal/enterprise-order-outbox',
    path: '/api/internal/enterprise-order-outbox',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalEnterpriseWebhookWorkerRoute =
  ApiInternalEnterpriseWebhookWorkerRouteImport.update({
    id: '/api/internal/enterprise-webhook-worker',
    path: '/api/internal/enterprise-webhook-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalExpirePaymentOrdersRoute =
  ApiInternalExpirePaymentOrdersRouteImport.update({
    id: '/api/internal/expire-payment-orders',
    path: '/api/internal/expire-payment-orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalSyncEnterpriseCatalogsRoute =
  ApiInternalSyncEnterpriseCatalogsRouteImport.update({
    id: '/api/internal/sync-enterprise-catalogs',
    path: '/api/internal/sync-enterprise-catalogs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMobileCatalogRoute = ApiMobileCatalogRouteImport.update({
  id: '/api/mobile/catalog',
  path: '/api/mobile/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileCheckoutRoute = ApiMobileCheckoutRouteImport.update({
  id: '/api/mobile/checkout',
  path: '/api/mobile/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileDeliveryQuoteRoute = ApiMobileDeliveryQuoteRouteImport.update({
  id: '/api/mobile/delivery-quote',
  path: '/api/mobile/delivery-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileMeRoute = ApiMobileMeRouteImport.update({
  id: '/api/mobile/me',
  path: '/api/mobile/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobilePaymentIntentRoute = ApiMobilePaymentIntentRouteImport.update({
  id: '/api/mobile/payment-intent',
  path: '/api/mobile/payment-intent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobilePaymentStatusRoute = ApiMobilePaymentStatusRouteImport.update({
  id: '/api/mobile/payment-status',
  path: '/api/mobile/payment-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMobileProfileRoute = ApiMobileProfileRouteImport.update({
  id: '/api/mobile/profile',
  path: '/api/mobile/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsWebhookRoute = ApiPaymentsWebhookRouteImport.update({
  id: '/api/payments/webhook',
  path: '/api/payments/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandIntegrationWebhookRoute =
  ApiBrandIntegrationWebhookRouteImport.update({
    id: '/api/brand/integration/webhook',
    path: '/api/brand/integration/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEnterpriseCatalogSyncRoute =
  ApiEnterpriseCatalogSyncRouteImport.update({
    id: '/api/enterprise/catalog/sync',
    path: '/api/enterprise/catalog/sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEnterpriseCatalogWebhookRoute =
  ApiEnterpriseCatalogWebhookRouteImport.update({
    id: '/api/enterprise/catalog/webhook',
    path: '/api/enterprise/catalog/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFinancingMerchantsMerchantIdHealthRoute =
  ApiFinancingMerchantsMerchantIdHealthRouteImport.update({
    id: '/api/financing/merchants/$merchantId/health',
    path: '/api/financing/merchants/$merchantId/health',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/two-factor': typeof TwoFactorRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/support': typeof AdminSupportRoute
  '/api/health': typeof ApiHealthRoute
  '/api/search': typeof ApiSearchRoute
  '/merchant/dashboard': typeof MerchantDashboardRoute
  '/merchant/login': typeof MerchantLoginRoute
  '/merchant/register': typeof MerchantRegisterRoute
  '/orders/$id': typeof OrdersIdRoute
  '/payment/preview': typeof PaymentPreviewRoute
  '/payment/return': typeof PaymentReturnRoute
  '/products/$id': typeof ProductsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/delivery/quote': typeof ApiDeliveryQuoteRoute
  '/api/email/webhook': typeof ApiEmailWebhookRoute
  '/api/internal/brand-integration-worker': typeof ApiInternalBrandIntegrationWorkerRoute
  '/api/internal/enterprise-order-outbox': typeof ApiInternalEnterpriseOrderOutboxRoute
  '/api/internal/enterprise-webhook-worker': typeof ApiInternalEnterpriseWebhookWorkerRoute
  '/api/internal/expire-payment-orders': typeof ApiInternalExpirePaymentOrdersRoute
  '/api/internal/sync-enterprise-catalogs': typeof ApiInternalSyncEnterpriseCatalogsRoute
  '/api/mobile/catalog': typeof ApiMobileCatalogRoute
  '/api/mobile/checkout': typeof ApiMobileCheckoutRoute
  '/api/mobile/delivery-quote': typeof ApiMobileDeliveryQuoteRoute
  '/api/mobile/me': typeof ApiMobileMeRoute
  '/api/mobile/payment-intent': typeof ApiMobilePaymentIntentRoute
  '/api/mobile/payment-status': typeof ApiMobilePaymentStatusRoute
  '/api/mobile/profile': typeof ApiMobileProfileRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/api/brand/integration/webhook': typeof ApiBrandIntegrationWebhookRoute
  '/api/enterprise/catalog/sync': typeof ApiEnterpriseCatalogSyncRoute
  '/api/enterprise/catalog/webhook': typeof ApiEnterpriseCatalogWebhookRoute
  '/api/financing/merchants/$merchantId/health': typeof ApiFinancingMerchantsMerchantIdHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/two-factor': typeof TwoFactorRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/support': typeof AdminSupportRoute
  '/api/health': typeof ApiHealthRoute
  '/api/search': typeof ApiSearchRoute
  '/merchant/dashboard': typeof MerchantDashboardRoute
  '/merchant/login': typeof MerchantLoginRoute
  '/merchant/register': typeof MerchantRegisterRoute
  '/orders/$id': typeof OrdersIdRoute
  '/payment/preview': typeof PaymentPreviewRoute
  '/payment/return': typeof PaymentReturnRoute
  '/products/$id': typeof ProductsIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/delivery/quote': typeof ApiDeliveryQuoteRoute
  '/api/email/webhook': typeof ApiEmailWebhookRoute
  '/api/internal/brand-integration-worker': typeof ApiInternalBrandIntegrationWorkerRoute
  '/api/internal/enterprise-order-outbox': typeof ApiInternalEnterpriseOrderOutboxRoute
  '/api/internal/enterprise-webhook-worker': typeof ApiInternalEnterpriseWebhookWorkerRoute
  '/api/internal/expire-payment-orders': typeof ApiInternalExpirePaymentOrdersRoute
  '/api/internal/sync-enterprise-catalogs': typeof ApiInternalSyncEnterpriseCatalogsRoute
  '/api/mobile/catalog': typeof ApiMobileCatalogRoute
  '/api/mobile/checkout': typeof ApiMobileCheckoutRoute
  '/api/mobile/delivery-quote': typeof ApiMobileDeliveryQuoteRoute
  '/api/mobile/me': typeof ApiMobileMeRoute
  '/api/mobile/payment-intent': typeof ApiMobilePaymentIntentRoute
  '/api/mobile/payment-status': typeof ApiMobilePaymentStatusRoute
  '/api/mobile/profile': typeof ApiMobileProfileRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/api/brand/integration/webhook': typeof ApiBrandIntegrationWebhookRoute
  '/api/enterprise/catalog/sync': typeof ApiEnterpriseCatalogSyncRoute
  '/api/enterprise/catalog/webhook': typeof ApiEnterpriseCatalogWebhookRoute
  '/api/financing/merchants/$merchantId/health': typeof ApiFinancingMerchantsMerchantIdHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/two-factor': typeof TwoFactorRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/support': typeof AdminSupportRoute
  '/api/health': typeof ApiHealthRoute
  '/api/search': typeof ApiSearchRoute
  '/merchant/dashboard': typeof MerchantDashboardRoute
  '/merchant/login': typeof MerchantLoginRoute
  '/merchant/register': typeof MerchantRegisterRoute
  '/orders/$id': typeof OrdersIdRoute
  '/payment/preview': typeof PaymentPreviewRoute
  '/payment/return': typeof PaymentReturnRoute
  '/products/$id': typeof ProductsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/delivery/quote': typeof ApiDeliveryQuoteRoute
  '/api/email/webhook': typeof ApiEmailWebhookRoute
  '/api/internal/brand-integration-worker': typeof ApiInternalBrandIntegrationWorkerRoute
  '/api/internal/enterprise-order-outbox': typeof ApiInternalEnterpriseOrderOutboxRoute
  '/api/internal/enterprise-webhook-worker': typeof ApiInternalEnterpriseWebhookWorkerRoute
  '/api/internal/expire-payment-orders': typeof ApiInternalExpirePaymentOrdersRoute
  '/api/internal/sync-enterprise-catalogs': typeof ApiInternalSyncEnterpriseCatalogsRoute
  '/api/mobile/catalog': typeof ApiMobileCatalogRoute
  '/api/mobile/checkout': typeof ApiMobileCheckoutRoute
  '/api/mobile/delivery-quote': typeof ApiMobileDeliveryQuoteRoute
  '/api/mobile/me': typeof ApiMobileMeRoute
  '/api/mobile/payment-intent': typeof ApiMobilePaymentIntentRoute
  '/api/mobile/payment-status': typeof ApiMobilePaymentStatusRoute
  '/api/mobile/profile': typeof ApiMobileProfileRoute
  '/api/payments/webhook': typeof ApiPaymentsWebhookRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/api/brand/integration/webhook': typeof ApiBrandIntegrationWebhookRoute
  '/api/enterprise/catalog/sync': typeof ApiEnterpriseCatalogSyncRoute
  '/api/enterprise/catalog/webhook': typeof ApiEnterpriseCatalogWebhookRoute
  '/api/financing/merchants/$merchantId/health': typeof ApiFinancingMerchantsMerchantIdHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/orders'
    | '/profile'
    | '/reset-password'
    | '/support'
    | '/two-factor'
    | '/admin/campaigns'
    | '/admin/dashboard'
    | '/admin/security'
    | '/admin/support'
    | '/api/health'
    | '/api/search'
    | '/merchant/dashboard'
    | '/merchant/login'
    | '/merchant/register'
    | '/orders/$id'
    | '/payment/preview'
    | '/payment/return'
    | '/products/$id'
    | '/admin/'
    | '/admin/orders/$orderId'
    | '/api/auth/$'
    | '/api/delivery/quote'
    | '/api/email/webhook'
    | '/api/internal/brand-integration-worker'
    | '/api/internal/enterprise-order-outbox'
    | '/api/internal/enterprise-webhook-worker'
    | '/api/internal/expire-payment-orders'
    | '/api/internal/sync-enterprise-catalogs'
    | '/api/mobile/catalog'
    | '/api/mobile/checkout'
    | '/api/mobile/delivery-quote'
    | '/api/mobile/me'
    | '/api/mobile/payment-intent'
    | '/api/mobile/payment-status'
    | '/api/mobile/profile'
    | '/api/payments/webhook'
    | '/admin/orders/'
    | '/api/brand/integration/webhook'
    | '/api/enterprise/catalog/sync'
    | '/api/enterprise/catalog/webhook'
    | '/api/financing/merchants/$merchantId/health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/orders'
    | '/profile'
    | '/reset-password'
    | '/support'
    | '/two-factor'
    | '/admin/campaigns'
    | '/admin/dashboard'
    | '/admin/security'
    | '/admin/support'
    | '/api/health'
    | '/api/search'
    | '/merchant/dashboard'
    | '/merchant/login'
    | '/merchant/register'
    | '/orders/$id'
    | '/payment/preview'
    | '/payment/return'
    | '/products/$id'
    | '/admin'
    | '/admin/orders/$orderId'
    | '/api/auth/$'
    | '/api/delivery/quote'
    | '/api/email/webhook'
    | '/api/internal/brand-integration-worker'
    | '/api/internal/enterprise-order-outbox'
    | '/api/internal/enterprise-webhook-worker'
    | '/api/internal/expire-payment-orders'
    | '/api/internal/sync-enterprise-catalogs'
    | '/api/mobile/catalog'
    | '/api/mobile/checkout'
    | '/api/mobile/delivery-quote'
    | '/api/mobile/me'
    | '/api/mobile/payment-intent'
    | '/api/mobile/payment-status'
    | '/api/mobile/profile'
    | '/api/payments/webhook'
    | '/admin/orders'
    | '/api/brand/integration/webhook'
    | '/api/enterprise/catalog/sync'
    | '/api/enterprise/catalog/webhook'
    | '/api/financing/merchants/$merchantId/health'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/orders'
    | '/profile'
    | '/reset-password'
    | '/support'
    | '/two-factor'
    | '/admin/campaigns'
    | '/admin/dashboard'
    | '/admin/security'
    | '/admin/support'
    | '/api/health'
    | '/api/search'
    | '/merchant/dashboard'
    | '/merchant/login'
    | '/merchant/register'
    | '/orders/$id'
    | '/payment/preview'
    | '/payment/return'
    | '/products/$id'
    | '/admin/'
    | '/admin/orders/$orderId'
    | '/api/auth/$'
    | '/api/delivery/quote'
    | '/api/email/webhook'
    | '/api/internal/brand-integration-worker'
    | '/api/internal/enterprise-order-outbox'
    | '/api/internal/enterprise-webhook-worker'
    | '/api/internal/expire-payment-orders'
    | '/api/internal/sync-enterprise-catalogs'
    | '/api/mobile/catalog'
    | '/api/mobile/checkout'
    | '/api/mobile/delivery-quote'
    | '/api/mobile/me'
    | '/api/mobile/payment-intent'
    | '/api/mobile/payment-status'
    | '/api/mobile/profile'
    | '/api/payments/webhook'
    | '/admin/orders/'
    | '/api/brand/integration/webhook'
    | '/api/enterprise/catalog/sync'
    | '/api/enterprise/catalog/webhook'
    | '/api/financing/merchants/$merchantId/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SupportRoute: typeof SupportRoute
  TwoFactorRoute: typeof TwoFactorRoute
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSupportRoute: typeof AdminSupportRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSearchRoute: typeof ApiSearchRoute
  MerchantDashboardRoute: typeof MerchantDashboardRoute
  MerchantLoginRoute: typeof MerchantLoginRoute
  MerchantRegisterRoute: typeof MerchantRegisterRoute
  PaymentPreviewRoute: typeof PaymentPreviewRoute
  PaymentReturnRoute: typeof PaymentReturnRoute
  ProductsIdRoute: typeof ProductsIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDeliveryQuoteRoute: typeof ApiDeliveryQuoteRoute
  ApiEmailWebhookRoute: typeof ApiEmailWebhookRoute
  ApiInternalBrandIntegrationWorkerRoute: typeof ApiInternalBrandIntegrationWorkerRoute
  ApiInternalEnterpriseOrderOutboxRoute: typeof ApiInternalEnterpriseOrderOutboxRoute
  ApiInternalEnterpriseWebhookWorkerRoute: typeof ApiInternalEnterpriseWebhookWorkerRoute
  ApiInternalExpirePaymentOrdersRoute: typeof ApiInternalExpirePaymentOrdersRoute
  ApiInternalSyncEnterpriseCatalogsRoute: typeof ApiInternalSyncEnterpriseCatalogsRoute
  ApiMobileCatalogRoute: typeof ApiMobileCatalogRoute
  ApiMobileCheckoutRoute: typeof ApiMobileCheckoutRoute
  ApiMobileDeliveryQuoteRoute: typeof ApiMobileDeliveryQuoteRoute
  ApiMobileMeRoute: typeof ApiMobileMeRoute
  ApiMobilePaymentIntentRoute: typeof ApiMobilePaymentIntentRoute
  ApiMobilePaymentStatusRoute: typeof ApiMobilePaymentStatusRoute
  ApiMobileProfileRoute: typeof ApiMobileProfileRoute
  ApiPaymentsWebhookRoute: typeof ApiPaymentsWebhookRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  ApiBrandIntegrationWebhookRoute: typeof ApiBrandIntegrationWebhookRoute
  ApiEnterpriseCatalogSyncRoute: typeof ApiEnterpriseCatalogSyncRoute
  ApiEnterpriseCatalogWebhookRoute: typeof ApiEnterpriseCatalogWebhookRoute
  ApiFinancingMerchantsMerchantIdHealthRoute: typeof ApiFinancingMerchantsMerchantIdHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/admin/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/admin/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/dashboard': {
      id: '/merchant/dashboard'
      path: '/merchant/dashboard'
      fullPath: '/merchant/dashboard'
      preLoaderRoute: typeof MerchantDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/login': {
      id: '/merchant/login'
      path: '/merchant/login'
      fullPath: '/merchant/login'
      preLoaderRoute: typeof MerchantLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/register': {
      id: '/merchant/register'
      path: '/merchant/register'
      fullPath: '/merchant/register'
      preLoaderRoute: typeof MerchantRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/payment/preview': {
      id: '/payment/preview'
      path: '/payment/preview'
      fullPath: '/payment/preview'
      preLoaderRoute: typeof PaymentPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/return': {
      id: '/payment/return'
      path: '/payment/return'
      fullPath: '/payment/return'
      preLoaderRoute: typeof PaymentReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/admin/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/admin/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/delivery/quote': {
      id: '/api/delivery/quote'
      path: '/api/delivery/quote'
      fullPath: '/api/delivery/quote'
      preLoaderRoute: typeof ApiDeliveryQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/webhook': {
      id: '/api/email/webhook'
      path: '/api/email/webhook'
      fullPath: '/api/email/webhook'
      preLoaderRoute: typeof ApiEmailWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/brand-integration-worker': {
      id: '/api/internal/brand-integration-worker'
      path: '/api/internal/brand-integration-worker'
      fullPath: '/api/internal/brand-integration-worker'
      preLoaderRoute: typeof ApiInternalBrandIntegrationWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/enterprise-order-outbox': {
      id: '/api/internal/enterprise-order-outbox'
      path: '/api/internal/enterprise-order-outbox'
      fullPath: '/api/internal/enterprise-order-outbox'
      preLoaderRoute: typeof ApiInternalEnterpriseOrderOutboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/enterprise-webhook-worker': {
      id: '/api/internal/enterprise-webhook-worker'
      path: '/api/internal/enterprise-webhook-worker'
      fullPath: '/api/internal/enterprise-webhook-worker'
      preLoaderRoute: typeof ApiInternalEnterpriseWebhookWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/expire-payment-orders': {
      id: '/api/internal/expire-payment-orders'
      path: '/api/internal/expire-payment-orders'
      fullPath: '/api/internal/expire-payment-orders'
      preLoaderRoute: typeof ApiInternalExpirePaymentOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/sync-enterprise-catalogs': {
      id: '/api/internal/sync-enterprise-catalogs'
      path: '/api/internal/sync-enterprise-catalogs'
      fullPath: '/api/internal/sync-enterprise-catalogs'
      preLoaderRoute: typeof ApiInternalSyncEnterpriseCatalogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/catalog': {
      id: '/api/mobile/catalog'
      path: '/api/mobile/catalog'
      fullPath: '/api/mobile/catalog'
      preLoaderRoute: typeof ApiMobileCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/checkout': {
      id: '/api/mobile/checkout'
      path: '/api/mobile/checkout'
      fullPath: '/api/mobile/checkout'
      preLoaderRoute: typeof ApiMobileCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/delivery-quote': {
      id: '/api/mobile/delivery-quote'
      path: '/api/mobile/delivery-quote'
      fullPath: '/api/mobile/delivery-quote'
      preLoaderRoute: typeof ApiMobileDeliveryQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/me': {
      id: '/api/mobile/me'
      path: '/api/mobile/me'
      fullPath: '/api/mobile/me'
      preLoaderRoute: typeof ApiMobileMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/payment-intent': {
      id: '/api/mobile/payment-intent'
      path: '/api/mobile/payment-intent'
      fullPath: '/api/mobile/payment-intent'
      preLoaderRoute: typeof ApiMobilePaymentIntentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/payment-status': {
      id: '/api/mobile/payment-status'
      path: '/api/mobile/payment-status'
      fullPath: '/api/mobile/payment-status'
      preLoaderRoute: typeof ApiMobilePaymentStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mobile/profile': {
      id: '/api/mobile/profile'
      path: '/api/mobile/profile'
      fullPath: '/api/mobile/profile'
      preLoaderRoute: typeof ApiMobileProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/webhook': {
      id: '/api/payments/webhook'
      path: '/api/payments/webhook'
      fullPath: '/api/payments/webhook'
      preLoaderRoute: typeof ApiPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brand/integration/webhook': {
      id: '/api/brand/integration/webhook'
      path: '/api/brand/integration/webhook'
      fullPath: '/api/brand/integration/webhook'
      preLoaderRoute: typeof ApiBrandIntegrationWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enterprise/catalog/sync': {
      id: '/api/enterprise/catalog/sync'
      path: '/api/enterprise/catalog/sync'
      fullPath: '/api/enterprise/catalog/sync'
      preLoaderRoute: typeof ApiEnterpriseCatalogSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enterprise/catalog/webhook': {
      id: '/api/enterprise/catalog/webhook'
      path: '/api/enterprise/catalog/webhook'
      fullPath: '/api/enterprise/catalog/webhook'
      preLoaderRoute: typeof ApiEnterpriseCatalogWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/financing/merchants/$merchantId/health': {
      id: '/api/financing/merchants/$merchantId/health'
      path: '/api/financing/merchants/$merchantId/health'
      fullPath: '/api/financing/merchants/$merchantId/health'
      preLoaderRoute: typeof ApiFinancingMerchantsMerchantIdHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OrdersRouteChildren {
  OrdersIdRoute: typeof OrdersIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdRoute: OrdersIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SupportRoute: SupportRoute,
  TwoFactorRoute: TwoFactorRoute,
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSupportRoute: AdminSupportRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSearchRoute: ApiSearchRoute,
  MerchantDashboardRoute: MerchantDashboardRoute,
  MerchantLoginRoute: MerchantLoginRoute,
  MerchantRegisterRoute: MerchantRegisterRoute,
  PaymentPreviewRoute: PaymentPreviewRoute,
  PaymentReturnRoute: PaymentReturnRoute,
  ProductsIdRoute: ProductsIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDeliveryQuoteRoute: ApiDeliveryQuoteRoute,
  ApiEmailWebhookRoute: ApiEmailWebhookRoute,
  ApiInternalBrandIntegrationWorkerRoute:
    ApiInternalBrandIntegrationWorkerRoute,
  ApiInternalEnterpriseOrderOutboxRoute: ApiInternalEnterpriseOrderOutboxRoute,
  ApiInternalEnterpriseWebhookWorkerRoute:
    ApiInternalEnterpriseWebhookWorkerRoute,
  ApiInternalExpirePaymentOrdersRoute: ApiInternalExpirePaymentOrdersRoute,
  ApiInternalSyncEnterpriseCatalogsRoute:
    ApiInternalSyncEnterpriseCatalogsRoute,
  ApiMobileCatalogRoute: ApiMobileCatalogRoute,
  ApiMobileCheckoutRoute: ApiMobileCheckoutRoute,
  ApiMobileDeliveryQuoteRoute: ApiMobileDeliveryQuoteRoute,
  ApiMobileMeRoute: ApiMobileMeRoute,
  ApiMobilePaymentIntentRoute: ApiMobilePaymentIntentRoute,
  ApiMobilePaymentStatusRoute: ApiMobilePaymentStatusRoute,
  ApiMobileProfileRoute: ApiMobileProfileRoute,
  ApiPaymentsWebhookRoute: ApiPaymentsWebhookRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  ApiBrandIntegrationWebhookRoute: ApiBrandIntegrationWebhookRoute,
  ApiEnterpriseCatalogSyncRoute: ApiEnterpriseCatalogSyncRoute,
  ApiEnterpriseCatalogWebhookRoute: ApiEnterpriseCatalogWebhookRoute,
  ApiFinancingMerchantsMerchantIdHealthRoute:
    ApiFinancingMerchantsMerchantIdHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
