import { createServerFn } from "@tanstack/react-start";
import { randomUUID } from "node:crypto";
import { z } from "zod";
import { getSql } from "@/lib/db";
import { authMiddleware, getAuthenticatedUserId } from "@/lib/auth/middleware";
import { requireAdminForUserId } from "@/lib/auth/authorization.server";
import { requireFreshSession } from "@/lib/auth/verify.server";
import { enforceRateLimit } from "@/lib/security/rate-limit.server";

const destinationSchema=z.object({type:z.enum(["product","merchant","category"]),id:z.string().trim().min(1).max(128)});
const campaignInput=z.object({merchantId:z.string().trim().min(1).max(128),productId:z.string().trim().min(1).max(128).optional(),name:z.string().trim().min(2).max(120),title:z.string().trim().min(2).max(120),subtitle:z.string().trim().max(180).optional(),imagePath:z.string().trim().max(500).optional(),ctaLabel:z.string().trim().min(1).max(40).optional(),destination:destinationSchema,placement:z.enum(["sponsored_ads","food_spotlight"]),startsAt:z.string().datetime(),endsAt:z.string().datetime(),targetCity:z.string().trim().min(2).max(80).optional(),targetCategory:z.string().trim().min(2).max(80).optional(),priority:z.number().int().min(0).max(10000),maxImpressions:z.number().int().min(1).max(1000000000).nullable().optional(),mobileVisible:z.boolean(),desktopVisible:z.boolean(),adminNotes:z.string().trim().max(2000).optional()}).superRefine((v,ctx)=>{if(new Date(v.endsAt)<=new Date(v.startsAt))ctx.addIssue({code:"custom",path:["endsAt"],message:"End time must be after start time"});if(v.placement==="food_spotlight"&&v.destination.type!=="product")ctx.addIssue({code:"custom",path:["destination"],message:"Food Spotlight must target a product"});});
export type AdminCampaignRow={id:string;merchantId:string;merchantName:string;productId:string|null;productName:string|null;placement:string;status:string;name:string;title:string;subtitle:string|null;ctaLabel:string|null;imagePath:string|null;destinationType:string;destinationId:string;startsAt:string;endsAt:string;targetCity:string|null;targetCategory:string|null;priority:number;maxImpressions:number|null;impressionCount:number;clickCount:number;version:number;adminNotes:string|null;rejectionReason:string|null;mobileVisible:boolean;desktopVisible:boolean};
export const loadAdminCampaigns=createServerFn({method:"GET"}).middleware([authMiddleware]).handler(async({context})=>{const adminId=getAuthenticatedUserId(context);await requireAdminForUserId(adminId);const sql=await getSql();const rows=await sql.query<any>(`select c.id,c.merchant_id,c.product_id,m.name merchant_name,p.name product_name,c.placement,c.status,c.name,c.title,c.subtitle,c.cta_label,c.image_path,c.destination_type,c.destination_id,c.starts_at,c.ends_at,c.target_city,c.target_category,c.priority,c.max_impressions,c.impression_count,c.click_count,c.version,c.admin_notes,c.rejection_reason,c.mobile_visible,c.desktop_visible from homepage_ad_campaigns c join merchants m on m.id=c.merchant_id left join products p on p.id=c.product_id order by c.created_at desc limit 200`);return rows.map(r=>({id:r.id,merchantId:r.merchant_id,merchantName:r.merchant_name,productId:r.product_id,productName:r.product_name,placement:r.placement,status:r.status,name:r.name,title:r.title,subtitle:r.subtitle,ctaLabel:r.cta_label,imagePath:r.image_path,destinationType:r.destination_type,destinationId:r.destination_id,startsAt:new Date(r.starts_at).toISOString(),endsAt:new Date(r.ends_at).toISOString(),targetCity:r.target_city,targetCategory:r.target_category,priority:Number(r.priority),maxImpressions:r.max_impressions==null?null:Number(r.max_impressions),impressionCount:Number(r.impression_count),clickCount:Number(r.click_count),version:Number(r.version),adminNotes:r.admin_notes,rejectionReason:r.rejection_reason,mobileVisible:Boolean(r.mobile_visible),desktopVisible:Boolean(r.desktop_visible)}));});
export const loadCampaignFormOptions=createServerFn({method:"GET"}).middleware([authMiddleware]).handler(async({context})=>{const adminId=getAuthenticatedUserId(context);await requireAdminForUserId(adminId);const sql=await getSql();const merchants=await sql.query<{id:string;name:string;city:string|null}>(`select id,name,city from merchants where status='active' and verified=true order by name limit 500`);const products=await sql.query<{id:string;merchant_id:string;name:string;category:string;listing_type:string;stock:number}>(`select id,merchant_id,name,category,listing_type,stock from products where status='active' order by created_at desc limit 2000`);return {merchants,products:products.map(p=>({...p,stock:Number(p.stock)}))};});
export const createAdminHomepageCampaign=createServerFn({method:"POST"}).middleware([authMiddleware]).validator(campaignInput).handler(async({data,context})=>{const adminId=getAuthenticatedUserId(context);await requireAdminForUserId(adminId);await requireFreshSession();await enforceRateLimit("admin-homepage-campaign-create",{windowSeconds:60,maxRequests:20,subject:adminId});const sql=await getSql();const id=`had_${randomUUID().replaceAll("-","")}`;const rows=await sql.query<{id:string}>(`insert into homepage_ad_campaigns(id,merchant_id,product_id,name,title,subtitle,image_path,cta_label,destination_type,destination_id,placement,status,starts_at,ends_at,target_city,target_category,priority,max_impressions,mobile_visible,desktop_visible,admin_notes,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,'draft',$12,$13,$14,$15,$16,$17,$18,$19,$20,$21) returning id`,[id,data.merchantId,data.destination.type==='product'?(data.productId??data.destination.id):null,data.name,data.title,data.subtitle??null,data.imagePath??null,data.ctaLabel??null,data.destination.type,data.destination.id,data.placement,data.startsAt,data.endsAt,data.targetCity??null,data.targetCategory??null,data.priority,data.maxImpressions??null,data.mobileVisible,data.desktopVisible,data.adminNotes??null,adminId]);if(!rows[0])throw new Error("Campaign could not be created");await sql.query(`select record_audit_event($1,$2,$3,$4,$5,$6,$7,$8::jsonb)`,["admin.homepage_campaign.created","homepage_ad",id,adminId,"admin",null,"success",JSON.stringify({placement:data.placement,destination:data.destination,startsAt:data.startsAt,endsAt:data.endsAt})]);return {id,status:"draft" as const};});
const updateSchema=campaignInput.extend({campaignId:z.string().trim().min(1).max(128),expectedVersion:z.number().int().min(1)});
export const updateAdminHomepageCampaign=createServerFn({method:"POST"}).middleware([authMiddleware]).validator(updateSchema).handler(async({data,context})=>{const adminId=getAuthenticatedUserId(context);await requireAdminForUserId(adminId);await requireFreshSession();await enforceRateLimit("admin-homepage-campaign-update",{windowSeconds:60,maxRequests:30,subject:adminId});const sql=await getSql();const rows=await sql.query<{id:string;version:number}>(`update homepage_ad_campaigns set merchant_id=$2,product_id=$3,name=$4,title=$5,subtitle=$6,image_path=$7,cta_label=$8,destination_type=$9,destination_id=$10,placement=$11,starts_at=$12,ends_at=$13,target_city=$14,target_category=$15,priority=$16,max_impressions=$17,mobile_visible=$18,desktop_visible=$19,admin_notes=$20,version=version+1,updated_at=now() where id=$1 and version=$21 and status in ('draft','scheduled','paused','rejected') returning id,version`,[data.campaignId,data.merchantId,data.destination.type==='product'?(data.productId??data.destination.id):null,data.name,data.title,data.subtitle??null,data.imagePath??null,data.ctaLabel??null,data.destination.type,data.destination.id,data.placement,data.startsAt,data.endsAt,data.targetCity??null,data.targetCategory??null,data.priority,data.maxImpressions??null,data.mobileVisible,data.desktopVisible,data.adminNotes??null,data.expectedVersion]);if(!rows[0])throw new Error("Campaign was changed, active, or no longer editable");await sql.query(`select record_audit_event($1,$2,$3,$4,$5,$6,$7,$8::jsonb)`,["admin.homepage_campaign.updated","homepage_ad",data.campaignId,adminId,"admin",null,"success",JSON.stringify({version:rows[0].version})]);return {id:rows[0].id,version:Number(rows[0].version)};});
const statusSchema=z.object({campaignId:z.string().trim().min(1).max(128),action:z.enum(["approve","pause","resume","reject","archive","end"]),reason:z.string().trim().max(1000).optional(),expectedVersion:z.number().int().min(1).optional()});
export const setAdminHomepageCampaignStatus=createServerFn({method:"POST"}).middleware([authMiddleware]).validator(statusSchema).handler(async({data,context})=>{const adminId=getAuthenticatedUserId(context);await requireAdminForUserId(adminId);await requireFreshSession();await enforceRateLimit("admin-homepage-campaign-status",{windowSeconds:60,maxRequests:40,subject:adminId});const sql=await getSql();const rows=await sql.query<{result:any}>(`select admin_set_homepage_campaign_status($1,$2,$3,$4,$5) result`,[data.campaignId,data.action,adminId,data.reason??null,data.expectedVersion??null]);await sql.query(`select record_audit_event($1,$2,$3,$4,$5,$6,$7,$8::jsonb)`,[`admin.homepage_campaign.${data.action}`,"homepage_ad",data.campaignId,adminId,"admin",null,"success",JSON.stringify({reason:data.reason??null})]);return rows[0]?.result??{id:data.campaignId};});
